name: post-6times-bot

on:
  schedule:
    - cron: "0 2,6,10,14,18,22 * * *"   # UTC → JST 3/7/11/15/19/23
  workflow_dispatch: {}                 # 手動実行も可能

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Verify secrets
        run: |
          [ -n "${{ secrets.DISCORD_BOT_TOKEN }}" ] || { echo "::error::Missing DISCORD_BOT_TOKEN"; exit 1; }
          [ -n "${{ secrets.CHANNEL_ID }}" ] || { echo "::error::Missing CHANNEL_ID"; exit 1; }

      - name: Post scheduled message via Bot REST
        env:
          TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python - <<'PY'
          import os, json, urllib.request, urllib.error, datetime
          from datetime import timedelta, timezone

          token = os.environ["TOKEN"]
          channel_id = os.environ["CHANNEL_ID"]

          # 現在JST（UTC+9）
          now = datetime.datetime.now(timezone.utc) + timedelta(hours=9)
          wd = ['月','火','水','木','金','土','日'][now.weekday()]
          hh = now.hour

          # 曜日×時刻の文面（必要に応じて編集）
          schedule = {
              '月': {11:"英雄★",15:"建築", 19:"兵士", 23:"科学", 3:"ドローン★",7:"英雄★"},
              '火': {11:"建築★",15:"兵士", 19:"科学", 23:"ドローン",3:"英雄",  7:"建築"},
              '水': {11:"兵士",  15:"科学★",19:"ドローン",23:"英雄",  3:"建築",  7:"兵士"},
              '木': {11:"科学",  15:"ドローン",19:"英雄★",23:"建築", 3:"兵士",  7:"科学"},
              '金': {11:"ドローン",15:"英雄",19:"建築★",23:"兵士", 3:"科学",  7:"ドローン"},
              '土': {11:"英雄★",15:"建築★",19:"兵士", 23:"科学", 3:"ドローン",7:"英雄"},
              '日': {11:"建築",  15:"兵士", 19:"科学", 23:"ドローン",3:"英雄",  7:"建築"},
          }
          item = schedule.get(wd, {}).get(hh, "（スケジュール未設定）")

          content = f"【{wd} {hh:02d}:00】本日の軍拡：{item}"
          payload = {"content": content}

          req = urllib.request.Request(
              f"https://discord.com/api/v10/channels/{channel_id}/messages",
              data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
              headers={"Authorization": f"Bot {token}", "Content-Type": "application/json"},
              method="POST"
          )
          try:
              with urllib.request.urlopen(req) as r:
                  print("Discord:", r.status)
          except urllib.error.HTTPError as e:
              print("HTTPError:", e.code, e.read().decode("utf-8","ignore"))
              raise
          PY
